### ISSUE TITLE
error when executing cysmotif with signalp 

### ISSUE THREAD

**Issue by Yhani14** [fallandar/cysmotifsearcher#2]
I try to use the command cysmotif_searcher.pl with signalp, but i always get this error message: 
"Can not open demo_motifs_orfonly_withM.fasta: No such file or directory"

this is my line command:

/cysmotif_searcher.pl -i demo.fasta -g -m motifs.txt 

What can i do to resolve this problem?

**Comment by fallandar** [comment]
You have used "-g" option which starts the processing from running signalP program and implies that you already have an input file needed for signalP (that is, demo_motifs_orfonly_withM.fasta that contains ORFs with motifs). This option is intended to resume motif searching from the last successful operation if some issues occurred with signalP.

signalP is enabled by default - you do not need to specify any options for using it (of course, if you have installed it previously and   indicated the path of its local installation in cysmotif_searcher.pl as described in manual). signalP should be installed separately if you want to use it - I cannot include it in my package due to copyright issues.
