### ISSUE TITLE
SignalP incorporation in the cysmotifsearcher pipeline

### ISSUE THREAD

**Issue by gaidaroc** [fallandar/cysmotifsearcher#6]
First of all, thank you for creating an opensource tool.

When it comes to my question... I'd like to use the -g option in this pipeline. I am relatively new to signalp usage, so it would be great if you could help me in using this pipeline with signalp. If what I understood from the log file is correct, it first translates the nt.fasta to nt_translated.fasta  then it's supposed to use signalp at this step. I replaced the path for signalp in the script. Currently, I have the 5.0b version of signalp (which is the only 5th version). However, cysmotifsearcher detected it as not "version 5.0". I modified the if statement there. But still, I am not seeing any orfonly_withM created, and it gives me the "no _orfonly_withM file" error every time I start the pipeline with -g command.

I would appreciate if you could help.

**Comment by fallandar** [comment]
Thank you for using my software. In general, it works as follows:
- Input file is translated (if needed)
- ORFs are revealed and motifs are searched in these ORFs (output - XXX_motifs_orfonly.fasta)
- ORFs not starting with M are removed (output - XXX_motifs_orfonly_withM.fasta)
- The output file obtained is supplied to signalP as input. Then the results of signalP are parsed and only the sequences having 'signal peptide', as defined by signalP threshold, are kept. In additions the sequence is split with blank into two parts - mature peptide and signal peptide (output file - XXX_motifs_orfonly_withM_signalP.fasta)
- sequences are filtered by length, and non-unique are removed - final stage

Thus, _orfonly_withM file should be created without using signalP. 

My suggestion is to try demo file provided on github repository (demo.fasta). Run the pipeline as 
cysmotif_searcher.pl -i demo.fasta -m motifs.txt 
If in this case you have the _orfonly_withM file, then the problem is somehow in your dataset

You can also check signalP by running, e.g.,
/your_path/signalp-5.0/bin/signalp -gff3 -org euk -fasta XXX.fasta >/dev/null 2>&
Your can use the following sequence containing signal peptide as a test (just put it in XXX.fasta file):

\>scaffold-AALA-2072124-Meliosma_cuneifolia*CYSRICH*
MALKATIFLLSSLLLVTSKASYNDITPYEEDTALFAALARPPFVAPSPVPILPPVNPSEcprlcqgrcklhsrprhcnrvcvtcCNRCKCVPPGTYGNKEMCGKCYTDMTTHGNRPKCP

The output will be gff file. If you do not obtain any output, then the problem is with signalP.

Please try these 2 steps and put the output here - this will help me to identify potential problems

**Comment by gaidaroc** [comment]
Thanks for the answer. 
The outputs are gff3 and signalp files, if run separately. 
- Ran this after symlinking all the necessary files to path (including signalp):
    $ cysmotif_searcher.pl -i demo.fasta -m motifs.txt && unzip ./demo_results/demo.zip
- Ran this after unzipping the onlyM.fasta which is in the created results folder:
    $ signalp -gff3 -org euk -fasta demo_motifs_orfonly_withM.fasta

SignalP-5.0. Starting fasta file reading...
Total proteins read: 2.
Organism: euk.
Starting protein prediction...
Temporary directory: /tmp/signalp5.082942709
Protein prediction done!
Generating output files...
Completed.

[demo_motifs_orfonly_withM.zip](https://github.com/fallandar/cysmotifsearcher/files/14232251/demo_motifs_orfonly_withM.zip)

No problems... Getting the above-mentioned gff3 and signalp5 files.
But when running this:
   $ cysmotif_searcher.pl -i demo.fasta -m motifs.txt -g
no output with this error:
Can not open demo_motifs_orfonly_withM.fasta: No such file or directory

**Comment by fallandar** [comment]
I think I have figured out the problem. In order to start processing with signalP, the command should be

$ cysmotif_searcher.pl -i demo_motifs_orfonly_withM.fasta -m motifs.txt -g

because demo.fasta is not used as real input in this case and the processing pipeline starts with demo_motifs_orfonly_withM.fasta. 

Try running the pipeline like this. I would agree that this call is not always straightforward, so I will change the input argument processing in next update in order to allow specifying files like demo.fasta as input (the program will also search for demo_orfonly_withM.fasta in this case)

**Comment by gaidaroc** [comment]
Hmm.. This time, I'm getting an error message saying that:
Can not open demo_motifs_orfonly_withM_motifs_orfonly_withM.fasta: No such file directory

**Comment by fallandar** [comment]
This is really strange because I tried this command line and got the correct result. Are you using the latest version of cysmotif_searcher? (3.3.3) Did not you forget to add -g option? I am asking because the suffix 'orfonly_withM' should not be added by program when starting with '-g' option.

**Comment by gaidaroc** [comment]
I'm using the latest version of cysmotif_searcher (3.3.3):
$program="cysmotif_searcher.pl";  
$version="3.3.3";
in the .pl file.
Got the rfonly_withM fasta from the initial run. Hence, I've got only the aa seqs of proteins only starting with methionine. Then, the code is:
$ cysmotif_searcher.pl -i demo_motifs_orfonly_withM.fasta -m motifs.txt -g
Error is:
Can not open demo_motifs_orfonly_withM_motifs_orfonly_withM.fasta: No such file directory

**Comment by fallandar** [comment]
What is the version of cysmotif_searcher you are using? (cysmotif_searcher.pl -- version). I cannot reproduce this error with version 3.3.3. Another guess is that signalP version is determined incorrectly, but 5.0b should not cause any problems anyway.

**Comment by gaidaroc** [comment]
$ cysmotif_searcheer.pl --version
You are using /home/.../cysmotif_searcher.pl version 3.3.3
Last update: April 12, 2023
Written by Andrew Shelenkov, CRIE

Also, as I have mentioned before, I have seen that the signalp version is recognized incorrectly no matter what, thus the signalp line used the signalp4's syntax, seeing this, I have altered the "if" statement, so that it only applied the signalp 5.0's syntax, which worked correctly. However, the above mentioned error was given. This is strange. Would you mind sharing the signalp version you have? Since 5.0 (not 5.0b) is not available for download, this might be the main reason for this. I'm seeing that the signalp is working, but the files created at the tmp directory with temporary names, and understandably, removed afterwards.

**Comment by fallandar** [comment]
Please download the version of signalP (5.0), which I am using, at this link:


I will remove the link after you download the file since I am not sure if the authors allow to post the direct links outside their site.

**Comment by gaidaroc** [comment]
Done. I'll try using it asap

Edit: Downloaded, used, the same result...
I wonder what is different in your system that your signalp works in the pipeline you've created.

**Comment by fallandar** [comment]
Possibly, there is something wrong with writing permissions for temporary dirs created by signalP when starting it from cysmotif pipeline. But I cannot reproduce this locally

**Comment by fallandar** [comment]
Cannot reproduce the problem. Probably, it is connected to signalP file permission
